### ISSUE TITLE
New bug related to latency bug fix

### ISSUE THREAD

**Issue by fireflymagic** [TTV-LOL/extensions#17]
We have fixed the bug that forced on low latency mode. Let us know if you are still experiencing the buffering, it should hopefully be fixed.

_Originally posted by @captainswain in https://github.com/TTV-LOL/extensions/issues/16#issuecomment-869076184_

I posted about it as a comment under the last thread but the new bug is that we *cannot* put low latency mode on at all now. It is essentially forced off permanently now, the button doesn't show up under the advanced section at all.

**Comment by captainswain** [comment]
We have pushed a fix for this. Literally inverted the previous bug on mistake lol.

Let me know if this is still an issue.

**Comment by blunttheking** [comment]
I'm still getting the same issue i was before; buffer size cant keep up at 1080 60 when the extension is on, regardless of if the stream supports low latency or not, the issue disappears when the extension is disabled.

**Comment by pixeltris** [comment]
@blunttheking this is due to method being used. The initial m3u8 request is proxied. All subsequent traffic goes directly through Twitch; however, it uses a Twitch server closest to the proxied location. This can struggle to keep up at source resolution (depending on your location).

There are three solutions to this:

1) Add more proxy server locations. It looks like the proxy is set somewhere near Russia, and you're likely in North America if I were to guess? A south american node would possibly help with this issue.
2) Stick to lower resolutions.
3) Use an alternative ad blocking method.

**Comment by captainswain** [comment]
@pixeltris could be totally correct in his assumptions.

Once we proxy the request then it's all on your peering to twitch, however, if you are in the US you should be hitting our south American relay servers. If you live in EU you should be hitting one of our Russian relay servers which could be causing some latency issues.  I'm investigating if there are ways to ensure better latency/load, but we are limited as we are taking a pretty hands-off proxying approach.

**Comment by pixeltris** [comment]
Yea those locations seem pretty reasonable and there's probably not much room to do any better like you said.

There's the possibility of using Turbo accounts to avoid getting ads without having to go through specific countries. Though I've not actually tested it and Twitch might have some throttling in place which prevents many requests from Turbo accounts.

**Comment by blunttheking** [comment]
@pixeltris that checks out then if thats how the extension works; I am in the US, and in a pretty rural area. My internet is comparatively pretty good compared to other people around me but overall still pretty lacking.

Thanks for all the help!
